language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=SaphireProject_identity-management -Dsonar.organization=saphireproject -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=b57f1334158a13580d439e041191e5341e2a2b13

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
