server:
  port: 8084
  contextPath: "/"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idm
    username: postgres
    password: postgres
    generate-ddl: false
  jpa:
    show-sql: false
    hibernate.ddl-auto: validate
